// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Week6;

namespace Test.Week6.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210625085649_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Week6.Client", b =>
                {
                    b.Property<string>("CF")
                        .HasMaxLength(16)
                        .HasColumnType("nchar(16)")
                        .IsFixedLength(true);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CF");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Test.Week6.Policy", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCF")
                        .HasColumnType("nchar(16)");

                    b.Property<float>("Instalment")
                        .HasColumnType("real");

                    b.Property<string>("Kind of Policy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Number");

                    b.HasIndex("ClientCF");

                    b.ToTable("Policy");

                    b.HasDiscriminator<string>("Kind of Policy").HasValue("Policy");
                });

            modelBuilder.Entity("Test.Week6.CarRC", b =>
                {
                    b.HasBaseType("Test.Week6.Policy");

                    b.Property<int>("Displacement")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Car Policy");
                });

            modelBuilder.Entity("Test.Week6.Life", b =>
                {
                    b.HasBaseType("Test.Week6.Policy");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Life Policy");
                });

            modelBuilder.Entity("Test.Week6.Theft", b =>
                {
                    b.HasBaseType("Test.Week6.Policy");

                    b.Property<int>("Coverage")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Theft Policy");
                });

            modelBuilder.Entity("Test.Week6.Policy", b =>
                {
                    b.HasOne("Test.Week6.Client", "Client")
                        .WithMany("Policies")
                        .HasForeignKey("ClientCF");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Test.Week6.Client", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
